# Generated by Django 3.1.5 on 2021-02-15 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elephant',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
