# Generated by Django 3.1.5 on 2021-03-16 23:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminops', '0007_pi_site_code'),
        ('elephants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresetSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('interval', models.DurationField()),
                ('max_feeds', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('name', models.CharField(max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
                ('elephant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elephants.elephant')),
                ('feeder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminops.feeder')),
                ('presets', models.ManyToManyField(to='elephants.Preset')),
            ],
        ),
    ]
