# Generated by Django 3.1.5 on 2021-03-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0002_presetschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elephant',
            name='rfid',
            field=models.CharField(max_length=50),
        ),
    ]
