# Generated by Django 3.1.5 on 2021-02-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0003_auto_20210215_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
