# Generated by Django 3.1.5 on 2021-02-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0004_schedule_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=14)),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='presets',
            field=models.ManyToManyField(to='elephants.Preset'),
        ),
    ]
