# Generated by Django 3.1.5 on 2021-03-30 00:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0004_auto_20210325_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='end_time_temp',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_time_temp',
        ),
        migrations.AddField(
            model_name='schedule',
            name='end_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
