# Generated by Django 3.1.6 on 2021-03-16 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0005_auto_20210316_1217'),
        ('elephants', '0005_auto_20210224_1703'),
    ]

    operations = [
    ]
