# Generated by Django 3.1.5 on 2021-03-09 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminops', '0007_pi_site_code'),
        ('elephants', '0005_auto_20210224_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='default',
        ),
        migrations.AddField(
            model_name='schedule',
            name='feeder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminops.feeder'),
        ),
    ]
