# Generated by Django 3.1.5 on 2021-03-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0006_auto_20210308_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
