# Generated by Django 3.1.6 on 2021-04-08 15:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Pi', max_length=50)),
                ('ip', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('port', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)])),
                ('path', models.CharField(max_length=200)),
                ('connected', models.BooleanField(default=False)),
                ('site_code', models.CharField(default='AAA', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Feeder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Feeder', max_length=50)),
                ('tag', models.CharField(max_length=10)),
                ('connected_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminops.pi')),
            ],
        ),
        migrations.CreateModel(
            name='Antenna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Antenna', max_length=50)),
                ('tag', models.CharField(max_length=10)),
                ('connected_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminops.pi')),
            ],
        ),
    ]
