# Generated by Django 3.1.5 on 2021-02-02 00:52
# This migration creates the initial superuser/admin.
# Created by Luke Evers

from django.db import migrations
from django.contrib.auth.models import User

def initialize_admin(apps, schema_editor):
    # create superuser with username 'admin', password 'admin'
    user = User.objects.create_superuser('admin','','admin')
    user.save()



class Migration(migrations.Migration):

    dependencies = [
        # depends on auth app for Users model
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(initialize_admin),
    ]