# Generated by Django 3.1.5 on 2021-02-09 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
                ('port', models.CharField(max_length=5)),
                ('path', models.URLField(validators=[django.core.validators.URLValidator(schemes=['smb'])])),
                ('connected', models.BooleanField(default=False)),
            ],
        ),
    ]