# Generated by Django 3.1.5 on 2021-02-09 11:22

from adminops.models import Pi
from django.db import migrations

def initializepis(apps, schema_editor):
    #create a few pi objects
    pi1 = Pi()
    pi1.name = "pi A"
    pi1.ip = "192.168.1.1"
    pi1.port = 1234
    pi1.path = "smb://someserver"
    pi1.connected = False
    pi1.save()

    pi2 = Pi()
    pi2.name = "pi B"
    pi2.ip = "192.168.1.2"
    pi2.port = 1234
    pi2.path = "smb://someserver2"
    pi2.connected = True
    pi2.save()

    pi3 = Pi()
    pi3.name = "pi C"
    pi3.ip = "192.168.1.3"
    pi3.port = 1234
    pi3.path = "smb://someserver3"
    pi3.connected = True
    pi3.save()


class Migration(migrations.Migration):

    dependencies = [
        ('adminops', '0002_pi'),
    ]

    operations = [
        migrations.RunPython(initializepis),
    ]
