# Generated by Django 3.1.5 on 2021-04-15 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminops', '0002_create_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeder',
            name='pin',
            field=models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(1)]),
        ),
    ]
