# Generated by Django 3.1.5 on 2021-04-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminops', '0002_create_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pi',
            name='ip',
            field=models.GenericIPAddressField(null=True, protocol='IPv4', unique=True),
        ),
        migrations.AlterField(
            model_name='pi',
            name='site_code',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
