# Generated by Django 3.1.5 on 2021-02-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminops', '0004_auto_20210209_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pi',
            name='ip',
            field=models.GenericIPAddressField(protocol='IPv4', unique=True),
        ),
    ]
