# Generated by Django 3.1.5 on 2021-02-16 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminops', '0005_auto_20210209_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='pi',
            name='name',
            field=models.CharField(default='Pi', max_length=50),
        ),
        migrations.CreateModel(
            name='Feeder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Feeder', max_length=50)),
                ('tag', models.CharField(max_length=10)),
                ('connected_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminops.pi')),
            ],
        ),
        migrations.CreateModel(
            name='Antenna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Antenna', max_length=50)),
                ('tag', models.CharField(max_length=10)),
                ('connected_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminops.pi')),
            ],
        ),
    ]
