# Generated by Django 3.1.6 on 2021-03-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminops', '0006_auto_20210216_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='pi',
            name='site_code',
            field=models.CharField(default='AAA', max_length=10),
        ),
    ]
