# Generated by Django 3.1.5 on 2021-04-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminops', '0007_pi_site_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pi',
            name='site_code',
            field=models.CharField(default='AAA', max_length=10, unique=True),
        ),
    ]
