# Generated by Django 3.1.5 on 2021-04-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminops', '0009_remove_pi_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pi',
            name='site_code',
            field=models.CharField(default='ABC', max_length=10, unique=True),
        ),
    ]
