# Generated by Django 3.1.5 on 2021-04-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminops', '0010_auto_20210405_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pi',
            name='ip',
            field=models.GenericIPAddressField(null=True, protocol='IPv4', unique=True),
        ),
    ]
