# Generated by Django 3.1.5 on 2021-04-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminops', '0011_auto_20210405_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pi',
            name='site_code',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
