# Generated by Django 3.1.6 on 2021-04-08 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TASK_UUID', models.CharField(max_length=36)),
                ('EXECUTE_AFTER_UNIX_TIME', models.CharField(max_length=10)),
                ('TARGET_SITE_CODE', models.CharField(max_length=3)),
                ('TARGET_FEEDER_NUMBER', models.CharField(max_length=2)),
                ('AMOUNT', models.CharField(max_length=1)),
                ('IF_RECIEVE_FROM_ANTENNA_NUMBER', models.CharField(max_length=2)),
                ('IF_RECIEVE_FROM_TAG_NUMBER', models.CharField(max_length=16)),
                ('INTERVAL_TIME', models.CharField(max_length=4)),
                ('EXPIRE_TIME', models.CharField(max_length=10)),
                ('REPEAT_X_TIMES', models.CharField(max_length=1)),
                ('COMPLETED_TIME', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RfidData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_tag_number', models.CharField(max_length=50)),
                ('unix_time', models.CharField(max_length=10)),
                ('site_code', models.CharField(max_length=3)),
                ('feeder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminops.feeder')),
            ],
        ),
    ]
