# Generated by Django 3.1.5 on 2021-03-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedingdata',
            name='antenna_number',
            field=models.CharField(max_length=10),
        ),
    ]
