# Generated by Django 3.1.5 on 2021-03-23 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminops', '0007_pi_site_code'),
        ('datalog', '0002_auto_20210316_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedingdata',
            name='antenna_number',
        ),
        migrations.AddField(
            model_name='feedingdata',
            name='feeder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminops.feeder'),
        ),
    ]
