# Generated by Django 3.1.5 on 2021-04-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalog', '0004_auto_20210323_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFIDLogData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaintext', models.CharField(max_length=100)),
                ('unix_time', models.CharField(max_length=20)),
                ('site_code', models.CharField(max_length=10)),
                ('antenna_tag', models.CharField(max_length=10)),
                ('rfid', models.CharField(max_length=50)),
            ],
        ),
    ]
