# Generated by Django 3.1.5 on 2021-04-01 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminops', '0008_auto_20210331_2242'),
        ('datalog', '0005_rfidlogdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfidlogdata',
            name='pi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adminops.pi'),
        ),
    ]
